import { faDrumstickBite } from "@fortawesome/free-solid-svg-icons";
interface DishInformation {
  price: number;
  name: string;
  vnName: string;
  id: string;
  haveImage: boolean;
  type: string;
}
const DISHES: Array<DishInformation> = [
  {
    price: 70,
    name: "Free-range chicken sauteed with lemongrass and chilli",
    vnName: "Gà xào sả ớt",
    type: "chicken",
    id: "G001",
    haveImage: true,
  },
  {
    price: 70,
    name: "Free-range chicken braised with coconut milk",
    vnName: "Gà khìa nước cốt dừa",
    type: "chicken",
    id: "G002",
    haveImage: true,
  },
  {
    price: 70,
    name: "Free-range chicken sauteedin green pepper sauce",
    vnName: "Gà sốt muối ớt xanh",
    type: "chicken",
    id: "G003",
    haveImage: true,
  },
  {
    price: 78,
    name: "Deep fried chicken wings with fish sauce",
    vnName: "Cánh gà chiên nước mắm",
    type: "chicken",
    id: "G004",
    haveImage: true,
  },
  {
    price: 70,
    name: "Braised chicken with ginger",
    vnName: "Gà kho gừng",
    type: "chicken",
    id: "G006",
    haveImage: true,
  },
  {
    price: 45,
    name: "Fried egg with minced pork and onion",
    vnName: "Trứng chiên thịt",
    type: "egg",
    id: "G007",
    haveImage: true,
  },
  {
    price: 62,
    name: "Fried egg with mushroom",
    vnName: "Trứng xào nấm",
    type: "egg",
    id: "G008",
    haveImage: true,
  },
  {
    price: 40,
    name: "Fried egg with tomato",
    vnName: "Trứng chiên cà chua",
    type: "egg",
    id: "G009",
    haveImage: true,
  },
  {
    price: 75,
    name: "Roasted duck sauteed with pickled cabbage",
    vnName: "Vịt quay xào dưa cải",
    type: "duck",
    id: "G010",
    haveImage: true,
  },
  {
    price: 70,
    name: "Sauteed duck with salt",
    vnName: "Vịt rang muối",
    type: "duck",
    id: "G011",
    haveImage: true,
  },
  {
    price: 70,
    name: "Sauteed duck with galangal",
    vnName: "Vịt rang riềng",
    type: "duck",
    id: "G012",
    haveImage: true,
  },
  {
    price: 70,
    name: "Boiled duck dip in fish sauce with ginger",
    vnName: "Vịt luộc chấm mắm gừng",
    type: "duck",
    id: "G013",
    haveImage: true,
  },
  {
    price: 75,
    name: "Sauteed duck with spicy sauce",
    vnName: "Vịt xào cay",
    type: "duck",
    id: "G015",
    haveImage: true,
  },
  {
    price: 58,
    name: "Steam minced pork in sauce of macerated fish",
    vnName: "Mắm chưng",
    type: "pork",
    id: "G016",
    haveImage: true,
  },
  {
    price: 57,
    name: "Vegetable cooked with fermented tofu",
    vnName: "",
    type: "other",
    id: "G018",
    haveImage: false,
  },
  {
    price: 65,
    name: "Pork belly cooked with palm sugar caramel",
    vnName: "Ba rọi kho đường thốt nốt",
    type: "pork",
    id: "G019",
    haveImage: true,
  },
  {
    price: 55,
    name: "Pork belly stir fried with shrimp paste",
    vnName: "Ba rọi xào mắm ruốc",
    type: "pork",
    id: "G021",
    haveImage: true,
  },
  {
    price: 72,
    name: "Roasted pork sauteed in garlic",
    vnName: "Heo quay cháy tỏi",
    type: "pork",
    id: "G022",
    haveImage: true,
  },
  {
    price: 65,
    name: "Fried pork belly with lemongrass",
    vnName: "Ba rọi chiên sả",
    type: "pork",
    id: "G023",
    haveImage: true,
  },
  {
    price: 75,
    name: "Fried pork chop in black pepper lime sauce",
    vnName: "Sườn non ram muối tiêu chanh",
    type: "pork",
    id: "G024",
    haveImage: true,
  },
  {
    price: 90,
    name: "Fried pork chop in sour and sweet sauce",
    vnName: "Sườn xào chua ngọt",
    type: "pork",
    id: "G025",
    haveImage: true,
  },
  {
    price: 55,
    name: "Round scad fish braised with garlic fish sauce",
    vnName: "Cá trê chiên chấm nước mắm xoài",
    type: "fish",
    id: "G027",
    haveImage: true,
  },
  {
    price: 61,
    name: "Fried fish cake sauteed with fish sauce",
    vnName: "Chả cá rim nước mắm",
    type: "fish",
    id: "G028",
    haveImage: true,
  },
  {
    price: 70.4,
    name: "Deep fried fish cake",
    vnName: "Chả cá chiên giòn",
    type: "fish",
    id: "G029",
    haveImage: true,
  },
  {
    price: 63,
    name: "Fried capelin and tamarind saute",
    vnName: "Cá diêu hồng quay me",
    type: "fish",
    id: "G031",
    haveImage: true,
  },
  {
    price: 95,
    name: "Stewed red tilapia In soy sauce",
    vnName: "Cá diêu hồng chưng tương",
    type: "fish",
    id: "G033",
    haveImage: true,
  },
  {
    price: 95,
    name: "Steamed red tilapia with spring onion",
    vnName: "",
    type: "fish",
    id: "G034",
    haveImage: false,
  },
  {
    price: 55,
    name: "000 Tofu deep fried with lemongrass and shrimp paste",
    vnName: "Đậu hủ ruốc sả",
    type: "tofu",
    id: "G035",
    haveImage: true,
  },
  {
    price: 80,
    name: "Tofu sauteed with seafood",
    vnName: "Đậu hủ sốt hải sản",
    type: "tofu",
    id: "G036",
    haveImage: true,
  },
  {
    price: 50,
    name: "Tofu deep fried with spring onion and soy sauce",
    vnName: "Đậu hủ chiên hành",
    type: "tofu",
    id: "G037",
    haveImage: true,
  },
  {
    price: 55,
    name: "Tofu stir fried with chilli and lemongrass",
    vnName: "Đậu hủ chiên sả ớt",
    type: "tofu",
    id: "G038",
    haveImage: true,
  },
  {
    price: 80,
    name: "Corned beef cooked in fish sauce and ginger",
    vnName: "Bắp bò luộc chấm mắm gừng",
    type: "beef",
    id: "G039",
    haveImage: true,
  },
  {
    price: 75,
    name: "Sauteed beef tripe with pickled cabbage",
    vnName: "Gân bò xào dưa cải",
    type: "beef",
    id: "G040",
    haveImage: true,
  },
  {
    price: 80,
    name: "Sbr-fried beef with lemongrass and chili",
    vnName: "Bò xào sả ớt",
    type: "beef",
    id: "G043",
    haveImage: true,
  },
  {
    price: 85,
    name: "Sauteed diced beef",
    vnName: "Bò lúc lắc",
    type: "beef",
    id: "G044",
    haveImage: true,
  },
  {
    price: 85,
    name: "Beef with green pepper sauce",
    vnName: "Bò sốt tiêu xanh",
    type: "beef",
    id: "G045",
    haveImage: true,
  },
  {
    price: 87,
    name: "Sauteed beef tripe 'Pah shiitaite mushroom",
    vnName: "Gân bò hầm nấm đông cô",
    type: "beef",
    id: "G046",
    haveImage: true,
  },
  {
    price: 75,
    name: "Stir fried clams with garlic, chili, and fish sauce",
    vnName: "Nghêu rim nước mắm",
    type: "seafood",
    id: "G047",
    haveImage: true,
  },
  {
    price: 83,
    name: "Stir fried shrimp with sea salt",
    vnName: "Tôm rang muối",
    type: "seafood",
    id: "G048",
    haveImage: true,
  },
  {
    price: 87,
    name: "Deep fried squid with salt and dried chili",
    vnName: "Mực chiên giòn",
    type: "seafood",
    id: "G049",
    haveImage: true,
  },
  {
    price: 75,
    name: "Stir fried dams with tamarind sauce",
    vnName: "Nghêu rim me",
    type: "seafood",
    id: "G051",
    haveImage: true,
  },
  {
    price: 88,
    name: "Deep fried squid with fish sauce",
    vnName: "Mực chiên nước mắm",
    type: "seafood",
    id: "G053",
    haveImage: true,
  },
  {
    price: 90,
    name: "Steamed squid with spring onion and ginger",
    vnName: "Mực hấp hành gừng",
    type: "seafood",
    id: "G055",
    haveImage: true,
  },
  {
    price: 65,
    name: "Clam and tomato soup",
    vnName: "Canh nghêu",
    type: "soup",
    id: "G056",
    haveImage: true,
  },
  {
    price: 60,
    name: "Beef soup with pickled cabbage",
    vnName: "Canh bò dưa cải",
    type: "soup",
    id: "G057",
    haveImage: true,
  },
  {
    price: 45,
    name: "Tofu soup",
    vnName: "Canh đậu hủ",
    type: "soup",
    id: "G058",
    haveImage: true,
  },
  {
    price: 65,
    name: "Bitter melon and fish ball soup",
    vnName: "Canh khổ qua chả cá",
    type: "soup",
    id: "G059",
    haveImage: true,
  },
  {
    price: 75,
    name: "Shrimp & sweet soup",
    vnName: "Canh chua tôm",
    type: "soup",
    id: "G060",
    haveImage: true,
  },
  {
    price: 60,
    name: "Green vegetable and prawn",
    vnName: "Canh cải xanh tôm",
    type: "soup",
    id: "G061",
    haveImage: true,
  },
  {
    price: 66,
    name: "Seaweed and tofu",
    vnName: "",
    type: "soup",
    id: "G063",
    haveImage: true,
  },
  {
    price: 66,
    name: "Calabash and shrimp",
    vnName: "Canh bầu nấu tôm",
    type: "soup",
    id: "G064",
    haveImage: true,
  },
  {
    price: 65,
    name: "Bitter melon and tofu",
    vnName: "Canh khổ qua đậu hủ",
    type: "soup",
    id: "G065",
    haveImage: true,
  },
  {
    price: 67,
    name: "Sour creeper leaves and chicken",
    vnName: "Canh gà lá giang",
    type: "soup",
    id: "G066",
    haveImage: true,
  },
  {
    price: 65,
    name: "Tofu skin and mushroom",
    vnName: "Canh nấm tàu hủ ky",
    type: "soup",
    id: "G067",
    haveImage: true,
  },
  {
    price: 65,
    name: "Mustard leaves and fish ball",
    vnName: "Canh cải xanh chả cá",
    type: "soup",
    id: "G068",
    haveImage: true,
  },
  {
    price: 58,
    name: "Luffa with mushroom and shrimp",
    vnName: "Canh mướp nấm tôm",
    type: "soup",
    id: "G069",
    haveImage: true,
  },
  {
    price: 65,
    name: "With five spice braised pork",
    vnName: "",
    type: "salad",
    id: "G070",
    haveImage: false,
  },
  {
    price: 75,
    name: "With shrimp and squid",
    vnName: "",
    type: "salad",
    id: "G071",
    haveImage: false,
  },
  {
    price: 75,
    name: "With corned beef",
    vnName: "",
    type: "salad",
    id: "G072",
    haveImage: false,
  },
  {
    price: 75,
    name: "With calabash and shrimp & pork",
    vnName: "",
    type: "salad",
    id: "G073",
    haveImage: false,
  },
  {
    price: 50,
    name: "With mushroom",
    vnName: "",
    type: "salad",
    id: "G074",
    haveImage: false,
  },
  {
    price: 70,
    name: "Ghem spring rolls",
    vnName: "",
    type: "salad",
    id: "G075",
    haveImage: false,
  },
  {
    price: 45,
    name: "Stir fried vegetable with garlic",
    vnName: "",
    type: "vegetables",
    id: "G076",
    haveImage: false,
  },
  {
    price: 65,
    name: "Stir fried vegetable with beef",
    vnName: "",
    type: "vegetables",
    id: "G077",
    haveImage: false,
  },
  {
    price: 57,
    name: "Stir fried vegetable with fermented tofu",
    vnName: "",
    type: "vegetables",
    id: "G078",
    haveImage: false,
  },
  {
    price: 55,
    name: "Boiled vegetable dipped in fermented tofu Gia",
    vnName: "",
    type: "vegetables",
    id: "G079",
    haveImage: false,
  },
  {
    price: 55,
    name: "Stir fried bean sprout with pork and chilli",
    vnName: "",
    type: "vegetables",
    id: "G080",
    haveImage: false,
  },
  {
    price: 55,
    name: "Stir fried baby corn and vegetable",
    vnName: "",
    type: "vegetables",
    id: "G081",
    haveImage: false,
  },
  {
    price: 10,
    name: "Steam rice in clay pot for 1 person",
    vnName: "",
    type: "side dishes",
    id: "G082",
    haveImage: false,
  },
  {
    price: 20,
    name: "Steam rice in bowl",
    vnName: "",
    type: "side dishes",
    id: "G083",
    haveImage: false,
  },
  {
    price: 10,
    name: "Pickled cabbage",
    vnName: "",
    type: "side dishes",
    id: "G084",
    haveImage: false,
  },
  {
    price: 10,
    name: "Kim chi",
    vnName: "",
    type: "side dishes",
    id: "G085",
    haveImage: false,
  },
  {
    price: 10,
    name: "Pickled aarden-egg",
    vnName: "",
    type: "side dishes",
    id: "G086",
    haveImage: false,
  },
  {
    price: 20,
    name: "Milk yogurt",
    vnName: "",
    type: "dessert",
    id: "G087",
    haveImage: false,
  },
  {
    price: 20,
    name: "Matcha yogurt",
    vnName: "",
    type: "dessert",
    id: "G088",
    haveImage: false,
  },
  {
    price: 20,
    name: "Iced Banana",
    vnName: "",
    type: "dessert",
    id: "G089",
    haveImage: false,
  },
  {
    price: 25,
    name: "Sweet tofu with ginger syrup the",
    vnName: "",
    type: "dessert",
    id: "G090",
    haveImage: false,
  },
  {
    price: 25,
    name: "Daily sweet dessert",
    vnName: "",
    type: "dessert",
    id: "G091",
    haveImage: false,
  },
  {
    price: 65,
    name: "Noodle with fried tofu & shrimp paste",
    vnName: "",
    type: "noodle with fried tofu & shrimp paste",
    id: "G092",
    haveImage: false,
  },
  {
    price: 40,
    name: "Noodle with fried tofu & fish sauce",
    vnName: "",
    type: "noodle with fried tofu & shrimp paste",
    id: "G093",
    haveImage: false,
  },
  {
    price: 45,
    name: "Noodle with boiled pork belly",
    vnName: "",
    type: "noodle with fried tofu & shrimp paste",
    id: "G094",
    haveImage: false,
  },
  {
    price: 40,
    name: "Noodle with fried tofu",
    vnName: "",
    type: "noodle with fried tofu & shrimp paste",
    id: "G095",
    haveImage: false,
  },
  {
    price: 20,
    name: "Pork roll with young green rice flakes",
    vnName: "",
    type: "noodle with fried tofu & shrimp paste",
    id: "G096",
    haveImage: false,
  },
  {
    price: 30,
    name: "Boiled pork belly",
    vnName: "",
    type: "noodle with fried tofu & shrimp paste",
    id: "G097",
    haveImage: false,
  },
  {
    price: 20,
    name: "Deep fried tofu",
    vnName: "",
    type: "noodle with fried tofu & shrimp paste",
    id: "G098",
    haveImage: false,
  },
  {
    price: 10,
    name: "Noodle",
    vnName: "",
    type: "noodle with fried tofu & shrimp paste",
    id: "G099",
    haveImage: false,
  },
  {
    price: 36,
    name: "Spring rolls with shrimp",
    vnName: "",
    type: "noodle with fried tofu & shrimp paste",
    id: "G100",
    haveImage: false,
  },
  {
    price: 80,
    name: "Mixed pork offals",
    vnName: "",
    type: "noodle with fried tofu & shrimp paste",
    id: "G101",
    haveImage: false,
  },
  {
    price: 80,
    name: "Fried pork offals",
    vnName: "",
    type: "noodle with fried tofu & shrimp paste",
    id: "G102",
    haveImage: false,
  },
  {
    price: 56,
    name: "Fried pig's pudding",
    vnName: "",
    type: "noodle with fried tofu & shrimp paste",
    id: "G103",
    haveImage: false,
  },
  {
    price: 80,
    name: "Noodle with pork stew in special-flavored soup",
    vnName: "",
    type: "noodle with pork stew soup & field crab hot pot",
    id: "G104",
    haveImage: false,
  },
  {
    price: 90,
    name: "Not pot with field crabs",
    vnName: "",
    type: "noodle with pork stew soup & field crab hot pot",
    id: "G105",
    haveImage: false,
  },
  {
    price: 50,
    name: "Field crabs",
    vnName: "",
    type: "noodle with pork stew soup & field crab hot pot",
    id: "G106",
    haveImage: false,
  },
  {
    price: 15,
    name: "Unhatched duck eggs",
    vnName: "",
    type: "noodle with pork stew soup & field crab hot pot",
    id: "G107",
    haveImage: false,
  },
  {
    price: 5,
    name: "Vegetables",
    vnName: "",
    type: "noodle with pork stew soup & field crab hot pot",
    id: "G108",
    haveImage: false,
  },
];
interface IngredientInformation {
  name: string;
  value: string;
}
const INGREDIENTS: Array<IngredientInformation> = [
  {
    name: "Gà",
    value: "chicken",
  },
  {
    name: "Vịt",
    value: "duck",
  },
  {
    name: "Trứng",
    value: "egg",
  },
  {
    name: "Heo",
    value: "pork",
  },
  {
    name: "Bò",
    value: "beef",
  },
  {
    name: "Đậu hủ",
    value: "tofu",
  },
  {
    name: "Canh",
    value: "soup",
  },
  {
    name: "Cá",
    value: "fish",
  },
];

const INGREDIENT_MAP: Map<string, Array<DishInformation>> = new Map<
  string,
  Array<DishInformation>
>();

INGREDIENTS.forEach((item) => INGREDIENT_MAP.set(item.value, []));

DISHES.forEach((dish) => {
  const a = INGREDIENT_MAP.get(dish.type);
  if (a) {
    a.push(dish);
  }
});

export { INGREDIENTS, DISHES, INGREDIENT_MAP };
